[package]
name = "exo-server"
version = "0.1.0"
edition = "2021"

[features]
range_checked = []
debug = []
arb = []
std = []

[dependencies]
rocket = "0.5.1"
socketcan = "3.5.0"
bitvec = { version = "1.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
dbc-codegen = "0.3"
